(()=>{'use strict';
const G=GameKit,$=id=>document.getElementById(id),store=G.create('monsoon-traders'),MAX_TURNS=60;
let match=null,mode='ai',screen='menu';
function shell(body){$('app').innerHTML=`<header class="mast"><div><p class="eyebrow">A game of shifting winds</p><h1 class="brand">Monsoon Traders</h1><p class="tagline">Fill the harbors. Read the wind. Claim the ports before your rival does.</p></div><div class="mast-actions"><button id="nav-home">Home</button><button id="nav-records">Records</button><button id="nav-profiles">Profiles</button></div></header>${body}<p class="footer">Monsoon Traders · A standalone browser game · Export profiles to keep your record</p>`;$('nav-home').onclick=()=>{if(match&&screen==='play'&&!confirm('Leave this match? It will not be recorded.'))return;match=null;menu()};$('nav-records').onclick=()=>{screen='records';shell(G.recordsHTML(store).replace('Fight record','Trade record'))};$('nav-profiles').onclick=profiles}
function profiles(){screen='profiles';shell(G.profilesHTML(store));G.wireProfiles(store,profiles)}
function menu(){screen='menu';shell(`<section class="panel"><p class="eyebrow">The spice route</p><h2>Every four turns, the wind changes.</h2><p class="lead">Choose one of your six ports and sail its cargo around the coast, one crate per stop. Cargo reaching your harbor scores. A clever landing can claim a rival's stock or fulfill the season's contract.</p><div class="button-row"><button class="primary" id="solo">Trade against the computer</button><button id="local">Local two-player</button></div></section><section class="panel"><h2>Rules of the coast</h2><div class="rules"><article><b>1 · Sail cargo</b><p>Tap one of your occupied ports. Its crates travel one by one with the wind, passing through your harbor but skipping your rival's. Every four turns, the wind reverses.</p></article><article><b>2 · Claim a market</b><p>Land your last crate in your own empty port and take the crates opposite it. Land at your highlighted contract port to earn two bonus coins. Land in your harbor to sail again.</p></article><article><b>3 · Close the route</b><p>When one side empties, the other takes its remaining cargo home. If neither side empties after sixty turns, both merchants bank their cargo. The larger harbor wins.</p></article></div></section>${G.recordsHTML(store).replace('Fight record','Recent voyages')}`);$('solo').onclick=()=>setup('ai');$('local').onclick=()=>setup('local')}
function setup(m){mode=m;screen='setup';const opts=store.profiles().filter(p=>p.id!==store.active().id);shell(`<section class="panel"><p class="eyebrow">Trade charter</p><h2>${m==='ai'?'Face the harbor master':'Choose a rival'}</h2><p class="muted">${m==='ai'?'You sail from the southern six ports. The computer owns the northern coast.':'Each merchant needs a separate local profile. The device will announce whose turn comes next.'}</p>${m==='local'?`<div class="formline"><label>First merchant: ${G.esc(store.active().name)}</label><label>Second merchant<select id="second"><option value="">Choose a profile</option>${opts.map(p=>`<option value="${G.esc(p.id)}">${G.esc(p.name)}</option>`).join('')}</select></label></div>${opts.length?'':'<p class="notice">Create a second profile before starting.</p>'}`:''}<div class="button-row"><button class="primary" id="begin" ${m==='local'&&!opts.length?'disabled':''}>Begin voyage</button><button id="back">Back</button></div></section>`);$('back').onclick=menu;$('begin').onclick=()=>{const second=m==='local'?$('second').value:null;if(m==='local'&&!second){alert('Choose a second profile.');return}match={pits:Array(12).fill(4),scores:[0,0],turn:0,plies:0,wind:1,contract:[2,9],log:[],players:[store.active().id,second],over:false};screen='play';play()}}
function owned(i,p){return p===0?i>=0&&i<6:i>=6&&i<12}
function sideEmpty(s,p){return s.pits.slice(p*6,p*6+6).every(n=>n===0)}
function contractFor(p,phase){return p*6+((2+phase)%6)}
function legal(s,p){return Array.from({length:6},(_,i)=>p*6+i).filter(i=>s.pits[i]>0)}
function clone(s){return{...s,pits:s.pits.slice(),scores:s.scores.slice(),contract:s.contract.slice(),log:s.log.slice()}}
function step(s,p,i){if(!owned(i,p)||s.pits[i]<1)throw Error('Choose one of your occupied ports.');const out=clone(s),n=out.pits[i];out.pits[i]=0;let pos=i,lastStore=false,landed=-1,remaining=n,justLeftStore=false;while(remaining){const boundary=p===0?(out.wind===1?5:0):(out.wind===1?11:6);if(pos===boundary&&!justLeftStore){out.scores[p]++;remaining--;lastStore=true;landed=-1;justLeftStore=true;continue}pos=(pos+out.wind+12)%12;out.pits[pos]++;remaining--;lastStore=false;landed=pos;justLeftStore=false}
 let captured=0,bonus=0;if(landed>=0&&owned(landed,p)){if(out.pits[landed]===1){const opposite=11-landed;if(out.pits[opposite]){captured=out.pits[opposite]+1;out.scores[p]+=captured;out.pits[opposite]=0;out.pits[landed]=0}}if(landed===out.contract[p]){bonus=2;out.scores[p]+=bonus}}
 out.plies++;let ended=sideEmpty(out,0)||sideEmpty(out,1)||out.plies>=MAX_TURNS;if(ended){for(let k=0;k<12;k++){out.scores[k<6?0:1]+=out.pits[k];out.pits[k]=0}out.over=true}else{if(out.plies%4===0){out.wind*=-1;const phase=out.plies/4;out.contract=[contractFor(0,phase),contractFor(1,phase)]}out.turn=lastStore?p:1-p}
 const detail=`${n} crate${n===1?'':'s'} from port ${i+1}${captured?`; captured ${captured}`:''}${bonus?'; contract +2':''}${lastStore&&!ended?'; sails again':''}${!ended&&out.plies%4===0?'; wind reversed':''}.`;out.log.push(`${s.plies+1}. ${playerName(s,p)} sailed ${detail}`);return out}
function playerName(s,p){const id=s.players[p];return id?store.profiles().find(x=>x.id===id)?.name||'Merchant':'Harbor master'}
function boardHTML(){const s=match,port=i=>{const available=!s.over&&s.turn===(mode==='ai'?0:s.turn)&&!(mode==='ai'&&s.turn===1)&&owned(i,s.turn)&&s.pits[i]>0;return`<button class="port ${available?'available':''} ${s.contract.includes(i)?'contract':''}" data-port="${i}" ${available?'':'disabled'} aria-label="Port ${i+1}, ${s.pits[i]} crates${s.contract.includes(i)?', contract port':''}"><small>PORT ${i+1}</small><strong>${s.pits[i]}</strong>${s.contract.includes(i)?'<em>★ +2</em>':''}</button>`};return`<div class="board" role="group" aria-label="Twelve ports and two harbors"><div class="harbor left"><b>${s.scores[1]}</b><span>${G.esc(playerName(s,1))}'s harbor</span></div>${[11,10,9,8,7,6].map(port).join('')}<div class="harbor right"><b>${s.scores[0]}</b><span>${G.esc(playerName(s,0))}'s harbor</span></div>${[0,1,2,3,4,5].map(port).join('')}</div><div class="board-note"><span>North: ${G.esc(playerName(s,1))}</span><span>${s.wind===1?'Wind → clockwise':'Wind ← counterclockwise'}</span><span>South: ${G.esc(playerName(s,0))}</span></div>`}
function play(){screen='play';const s=match,p=s.turn;const next=4-s.plies%4;const who=playerName(s,p);shell(`<section class="panel"><div class="spread"><div><p class="eyebrow">Voyage ${s.plies+1} · ${next} turn${next===1?'':'s'} until wind changes</p><h2>${G.esc(who)} sails next</h2><p class="muted">Choose an occupied ${p===0?'southern':'northern'} port. The gold rings show legal choices. Contracts are marked ★.</p></div><span class="sail" aria-label="${s.wind===1?'Clockwise':'Counterclockwise'} wind">${s.wind===1?'↻':'↺'}</span></div>${boardHTML()}<div class="market"><div class="stat"><b>${s.scores[0]}</b><span>${G.esc(playerName(s,0))}'s coins</span></div><div class="stat"><b>${s.scores[1]}</b><span>${G.esc(playerName(s,1))}'s coins</span></div><div class="stat"><b>+2</b><span>Land at your ★ contract port</span></div></div></section><section class="panel"><h3>Voyage log</h3><ol class="log">${s.log.slice(-10).reverse().map(x=>`<li>${G.esc(x)}</li>`).join('')}</ol></section>`);document.querySelectorAll('[data-port]').forEach(b=>b.onclick=()=>turn(+b.dataset.port));if(mode==='ai'&&p===1)setTimeout(ai,250)}
function turn(i){if(match.over||!owned(i,match.turn)||!match.pits[i]||(mode==='ai'&&match.turn===1))return;const old=match.turn;match=step(match,old,i);after(old)}
function after(old){if(match.over){finish();return}if(mode==='local'){const next=match.turn;document.getElementById('app').innerHTML='';G.handoff(playerName(match,next),next===old?'Your final crate reached home. Take another turn.':'Take the device and plan your next voyage.',play)}else play()}
function ai(){if(!match||match.over||match.turn!==1||screen!=='play')return;const choices=legal(match,1);let best=choices[0],value=-Infinity;for(const i of choices){const test=step(match,1,i);const score=(test.scores[1]-match.scores[1])*2+(test.over?(test.scores[1]-test.scores[0])*10:0)+(test.turn===1?2:0)+Math.random()*1.5;if(score>value){value=score;best=i}}match=step(match,1,best);after(1)}
function finish(){screen='result';const s=match,w=s.scores[0]===s.scores[1]?-1:s.scores[0]>s.scores[1]?0:1,winId=w<0?null:s.players[w];store.record(s.players,winId,mode==='ai'?'Solo':'Local two-player',s.log,`${s.scores[0]}–${s.scores[1]} coins.`);
 shell(`<section class="panel"><p class="eyebrow">Trade season complete</p><h2>${w<0?'The harbors are tied.':`${G.esc(playerName(s,w))} claims the coast.`}</h2><p class="lead">${G.esc(playerName(s,0))}: ${s.scores[0]} coins · ${G.esc(playerName(s,1))}: ${s.scores[1]} coins.</p><div class="button-row"><button class="primary" id="again">Trade again</button><button id="home">Home</button></div></section><section class="panel"><h3>Voyage record</h3><ol class="log">${s.log.map(x=>`<li>${G.esc(x)}</li>`).join('')}</ol></section>`);$('again').onclick=()=>setup(mode);$('home').onclick=menu}
menu();
})();
